- name: Proxmox
  hosts: all
  gather_facts: true
  become: true
  vars:
    sops: "{{ lookup('community.sops.sops', 'vars.enc.yaml') | ansible.builtin.from_yaml }}"
    # # ansible_user: '{{ sops.ansible_user }}'
    # # ansible_ssh_pass: '{{ sops.ansible_ssh_pass }}'
    ssh_user: '{{ sops.ssh_user }}'
    ssh_user_password: '{{ sops.ansible_ssh_pass }}'
  roles:
#    - role: update
#      when: inventory_hostname in groups['proxmox']
#    - role: ssh
#      when: inventory_hostname in groups['proxmox']
#    - role: nfs
#      when: inventory_hostname in groups['proxmox']
#    - role: containers
#      when: inventory_hostname in groups['proxmox']
    - role: vms
      when: inventory_hostname in groups['proxmox']
#    - role: k3s_cluster
#      when: inventory_hostname in groups['k3s']
#      tags: ['k3s']
