---
- name: Apt get updates
  ansible.builtin.apt:
    update-cache: true
    cache_valid_time: 86400 # One day

- name: Install aptitude and python3-proxmoxer
  ansible.builtin.apt:
    name:
      - aptitude
      - python3-proxmoxer
    state: present
    update_cache: false

- name: Check for upgradeable packages
  ansible.builtin.apt:
    upgrade: true
  check_mode: true
  register: upgradable

- name: Show Upgradable packages
  ansible.builtin.debug:
    msg: '{{ upgradable.stdout_lines }}'

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Ensure sudo package is installed
  ansible.builtin.package:
    name: sudo
    state: present

- name: Generate required locales
  ansible.builtin.command:
    cmd: locale-gen en_IE.UTF-8 en_US.UTF-8
    creates: /usr/lib/locale/en_US.utf8
  become: true

- name: Check current default locale
  ansible.builtin.command:
    cmd: 'grep LANG= /etc/default/locale'
  register: current_locale
  ignore_errors: true
  changed_when: false

- name: Set default locale
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    line: 'LANG=en_US.UTF-8'
    create: true
    mode: '0644'
  become: true
  when: current_locale.stdout.find('LANG=en_US.UTF-8') == -1

- name: Ensure correct permissions for locale file
  ansible.builtin.file:
    path: /etc/default/locale
    owner: root
    group: root
    mode: '0644'
  become: true
