# roles/vms/tasks/main.yaml
---
- name: Clone template for each node
  community.general.proxmox_kvm:
    api_host: '{{ sops.pm_api_host }}'
    api_user: '{{ sops.pm_api_user }}'
    api_password: '{{ sops.pm_api_password }}'
    node: '{{ sops.pm_node }}'
    clone: '{{ vms_existing_template }}'
    vmid: '{{ vms_existing_template }}'
    newid: '{{ item.id }}'
    name: '{{ item.name }}'
    storage: '{{ vms_storage_pool }}'
  loop: "{{ vms_nodes }}"
  register: cloned_vms

- name: Ensure /root/home-lab directory exists
  ansible.builtin.file:
    path: /root/home-lab
    state: directory
    mode: '0755'
  become: true

- name: Add cloud-init resize commands
  ansible.builtin.shell: |
    qm resize {{ item.id }} scsi0 +7G
    touch /root/home-lab/{{ item.id }}-scsi0-resized
  args:
    creates: '/root/home-lab/{{ item.id }}-scsi0-resized'
  loop: "{{ vms_nodes }}"
  when: cloned_vms is success

- name: Update VM configurations
  community.general.proxmox_kvm:
    api_host: '{{ sops.pm_api_host }}'
    api_user: '{{ sops.pm_api_user }}'
    api_password: '{{ sops.pm_api_password }}'
    node: '{{ sops.pm_node }}'
    vmid: '{{ item.id }}'
    cores: '{{ item.cpu }}'
    memory: '{{ item.memory }}'
    ciuser: '{{ sops.k3s_ciuser }}'
    cipassword: '{{ sops.k3s_cipassword }}'
    sshkeys: '{{ vms_pubkey }}'
    ipconfig:
      ipconfig0: 'ip={{ vms_base_ip }}.{{ item.ip_last_octet }}/24,gw={{ vms_base_ip }}.1'
    update: true
  loop: "{{ vms_nodes }}"
  when: cloned_vms is success

- name: Start VMs
  community.general.proxmox_kvm:
    api_host: '{{ sops.pm_api_host }}'
    api_user: '{{ sops.pm_api_user }}'
    api_password: '{{ sops.pm_api_password }}'
    node: '{{ sops.pm_node }}'
    vmid: '{{ item.id }}'
    state: started
  loop: "{{ vms_nodes }}"
  when: cloned_vms is success

- name: Wait for VMs to be ready
  ansible.builtin.wait_for:
    host: "{{ vms_base_ip }}.{{ item.ip_last_octet }}"
    port: 22
    timeout: 180
  loop: "{{ vms_nodes }}"
  when: cloned_vms is success
