---
- name: Download proxmox container templates
  community.general.proxmox_template:
    node: '{{ sops.pm_node }}'
    api_host: '{{ sops.pm_api_host }}'
    api_user: '{{ sops.pm_api_user }}'
    api_password: '{{ sops.pm_api_password }}'
    storage: local
    content_type: vztmpl
    template: '{{ item }}'
  loop: '{{ sops.templates }}'

- name: Create container
  community.general.proxmox:
    api_host: '{{ sops.pm_api_host }}'
    api_user: '{{ sops.pm_api_user }}'
    api_password: '{{ sops.pm_api_password }}'
    node: '{{ sops.pm_node }}'
    vmid: '{{ sops.container_id }}'
    hostname: ansible-ct-01
    password: password
    pubkey: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
    ostemplate: 'local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst' # TODO make more dynamic to get from var
    unprivileged: true
    cores: 1
    memory: 1024
    swap: 512
    netif: '{"net0":"name=eth0,gw=192.168.0.1,ip=192.168.0.72/24,bridge=vmbr0"}' # TODO more dynamic IP address
    storage: 'local-lvm'
    onboot: true
  register: create_container

- name: Sleep for 4 seconds
  ansible.builtin.pause:
    seconds: 4

- name: Start container
  community.general.proxmox:
    api_user: '{{ sops.pm_api_user }}'
    api_password: '{{ sops.pm_api_password }}'
    api_host: '{{ sops.pm_api_host }}'
    node: '{{ sops.pm_node }}'
    hostname: ansible-ct-01
    unprivileged: true
    state: started
